### ISSUE TITLE
Allow Paragraphs as Submissions

### ISSUE THREAD

**Issue by ZempTime** [excid3/feedforward.io#6]
this: http://feedforward.io/recommended/21 is ugly

I wanted to quote this:

> To begin a new novel, I look for the biggest problem in my life that I can't solve or tolerate. Something that drives me nuts, but I can't fix. Then I find a metaphor that allows me to explore the problem, exaggerating and expanding it beyond reason. I build it up to the worst scenario possible and then find a way to solve it. By the time the book is done, I've exhausted all of my emotions around the original problem. Whatever it was, it no longer bothers me. And typically, during the time of writing, the problem has resolved itself. It's like magic. Try it. It will keep you alive in this world of bullshit.

because its great. so my suggestion is, allow people to simply submit a limited paragraph or quote, so I can share thoughts with equal expediency as links. Not twitter, longer form, but something like this is missing.

so on this page:
<img width="830" alt="screen shot 2015-09-29 at 5 54 36 pm" src="https://cloud.githubusercontent.com/assets/3596468/10180562/d54689fc-66d3-11e5-849b-a806aa06ea90.png">

adding an 'or' option with a text area that will be displayed instead of the link, if its present, but keeping the link around to pull in the other stuff you need

**Comment by ZempTime** [comment]
nevermind, all of these things I can do from the edit screen!

**Comment by excid3** [comment]
Sweet! Yeah the stupid OpenGraph parser isn't very wise when it doesn't have actual results so you get messed up things like this. Paul Graham essays are the worst.
